version: '3.8'

services:
  landing-nginx:
    image: nginx:alpine
    container_name: calories-landing
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./landing.html:/usr/share/nginx/html/index.html:ro
      - ./robots.txt:/usr/share/nginx/html/robots.txt:ro
      - ./sitemap.xml:/usr/share/nginx/html/sitemap.xml:ro
      - ./yandex_841d1740cc0f06a7.html:/usr/share/nginx/html/yandex_841d1740cc0f06a7.html:ro
      - ./_nuxt:/usr/share/nginx/html/_nuxt:ro
      - ./images:/usr/share/nginx/html/images:ro
      - ./blog:/usr/share/nginx/html/blog:ro
      - ./privacy:/usr/share/nginx/html/privacy:ro
      - ./terms:/usr/share/nginx/html/terms:ro
      - ./favicon.ico:/usr/share/nginx/html/favicon.ico:ro
      - ./favicon.png:/usr/share/nginx/html/favicon.png:ro
      - ./logo.jpg:/usr/share/nginx/html/logo.jpg:ro
      - ./nginx-simple.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
