version: '3.8'

services:
  calories-bot:
    image: ghcr.io/rigsbey/calories_notebook:latest
    container_name: calories-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_CREDENTIALS_PATH=credentials.json
    volumes:
      - /opt/calories-bot/logs:/app/logs
      - /opt/calories-bot/temp_photos:/app/temp_photos
      - ./caloriesbot-949dd-firebase-adminsdk-fbsvc-4ecc1b1ad9.json:/app/caloriesbot-949dd-firebase-adminsdk-fbsvc-4ecc1b1ad9.json:ro
      - ./credentials.json:/app/credentials.json:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
