// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/3/2025, 1:02:20 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/kamil/PycharmProjects/calories_notebook/landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kamil/PycharmProjects/calories_notebook/landing/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kamil/PycharmProjects/calories_notebook/landing/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kamil/PycharmProjects/calories_notebook/landing/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kamil/PycharmProjects/calories_notebook/landing/plugins/**/*.{js,ts,mjs}","/Users/kamil/PycharmProjects/calories_notebook/landing/composables/**/*.{js,ts,mjs}","/Users/kamil/PycharmProjects/calories_notebook/landing/utils/**/*.{js,ts,mjs}","/Users/kamil/PycharmProjects/calories_notebook/landing/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kamil/PycharmProjects/calories_notebook/landing/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kamil/PycharmProjects/calories_notebook/landing/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kamil/PycharmProjects/calories_notebook/landing/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;