name: Deploy Calories Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Создаем директории если их нет
          mkdir -p /opt/calories-bot/{logs,temp_photos}
          
          # Переходим в рабочую директорию
          cd /opt/calories-bot
          
          # Скачиваем docker-compose файл
          curl -o docker-compose.prod.yml https://raw.githubusercontent.com/${{ github.repository }}/main/docker-compose.prod.yml
          
          # Создаем .env файл с секретами
          cat > .env <<EOF
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
          EOF
          
          # Устанавливаем правильные права
          chmod -R 777 logs temp_photos
          
          # Останавливаем старый контейнер
          docker-compose -f docker-compose.prod.yml down || true
          
          # Удаляем старый образ
          docker rmi ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest || true
          
          # Запускаем новый контейнер
          docker-compose -f docker-compose.prod.yml pull
          docker-compose -f docker-compose.prod.yml up -d
          
          # Проверяем статус
          docker-compose -f docker-compose.prod.yml ps
          
          # Показываем логи
          sleep 5
          docker-compose -f docker-compose.prod.yml logs --tail 10
